####################################################################
#### viya-services-vars.yml                                     ####
####################################################################
#### Author: SAS Institute Inc.                                 ####
####################################################################
#### DISCLAIMER                                                 ####
####################################################################
#### This Ansible Playbook is provided as-is, without warranty  ####
#### of any kind, either express or implied, including, but not ####
#### limited to, the implied warranties of merchantability,     ####
#### fitness for a particular purpose, or non-infringement.     ####
#### SAS Institute shall not be liable whatsoever for any       ####
#### damages arising out of the use of this documentation and   ####
#### code, including any direct, indirect, or consequential     ####
#### damages. SAS Institute reserves the right to alter or      ####
#### abandon use of this documentation and code at any time.    ####
#### In addition, SAS Institute will provide no support for the ####
#### materials contained herein.                                ####
####################################################################
---
########################################
# Variables used in playbooks
########################################
host_connection_timer: 5     #seconds
svas_retry_count: 2
svas_delay_timer: 2          #seconds
enable_stray_cleanup: false  #stray processes cleanup

########################################
# Commands used in playbooks
########################################
sasps_cmd: ps -ef|grep -E '/opt/sas/spre/|/opt/sas/viya/'|grep -v grep|tail -1
rhel_url_scraping_cmd: 'host=$(hostname -f);cat /etc/httpd/conf.d/proxy.conf|grep ProxyPass|grep -e "/SAS"|awk "{print \$2}"|sort|uniq|sed "s/^/http:\/\/"$host"/"'
sles_url_scraping_cmd: 'host=$(hostname -f);cat /etc/apache2/conf.d/proxy.conf|grep ProxyPass|grep -e "/SAS"|awk "{print \$2}"|sort|uniq|sed "s/^/http:\/\/"$host"/"'
list_services_cmd: ls /etc/init.d/sas-viya*|awk -F '/' '{print $NF}'|grep -vE "\-all\-|\-consul\-|\-vault\-|\-httpproxy\-|\-rabbitmq\-|\-sasdatasvrc\-|\-pgpoolc\-|\-cascontroller\-"
